"""Service page data for 247hrsCare.com"""

SERVICES = [
 dict(slug="24-hour-home-care", name="24-Hour Home Care", icon="clock", ctype="24-hour",
  title="24-Hour Home Care: Round-the-Clock Caregivers at Home",
  desc="How 24-hour home care works, what it costs, shift vs live-in models, and how to get matched with vetted 24/7 caregivers near you — free.",
  intro="24-hour home care means a trained caregiver is awake and on duty in the home at all times, usually by rotating two or three caregivers across 8–12 hour shifts. It is the closest thing to a care facility's level of supervision while your loved one stays in the place they know best.",
  who=["People at high risk of falls who need help getting up at night","Advanced dementia with wandering, sundowning or night-time confusion","Late-stage illness, palliative care or recovery after major surgery","Anyone who cannot safely be left alone for even short periods","Families whose own caregivers are exhausted and need full relief"],
  includes=["Continuous awake supervision, day and night","Bathing, dressing, toileting, incontinence care and repositioning","Medication reminders and symptom logs for the family and nurse","Meal preparation, hydration tracking and light housekeeping","Safe transfers, mobility support and fall-prevention routines","Companionship, cognitive activities and family updates"],
  cost="Non-medical in-home care has a U.S. national median of about $35 per hour (CareScout Cost of Care Survey 2025). At 24 hours a day that is roughly $840 per day, or about $25,000+ per month before agency discounts. Live-in care is often priced as a lower daily rate because the caregiver sleeps — see our live-in care guide and use the cost calculator for your own numbers.",
  faqs=[("What is the difference between 24-hour care and live-in care?","24-hour care uses two or three caregivers working awake shifts so someone is always alert. Live-in care uses one caregiver who lives in the home and must receive an uninterrupted sleep break and meal breaks, so it suits people who sleep through most nights."),
        ("Does Medicare pay for 24-hour home care?","Generally no. Original Medicare covers part-time, intermittent skilled home health, not round-the-clock custodial care. Long-term care insurance, VA benefits, some Medicaid waiver programs and private funds are the usual payment sources."),
        ("How fast can 24-hour care start?","Many agencies can staff within 24–72 hours for urgent cases. Having a care plan, medication list and home-access details ready speeds up the start."),
        ("Can we use 24-hour care for just a few weeks?","Yes. Short-term 24-hour care is common after hospital discharge or during a family crisis, and agencies typically allow you to step down to fewer hours later.")]),
 dict(slug="live-in-care", name="Live-In Care", icon="home", ctype="live-in",
  title="Live-In Care: One Dedicated Caregiver Living in the Home",
  desc="Live-in care explained: how it differs from 24-hour shift care, sleep-break rules, typical costs and how to find a trusted live-in caregiver.",
  intro="With live-in care, one primary caregiver stays in the home for several days at a time, providing help throughout the day and being present at night. It offers continuity — the same familiar face — often at a lower cost than 24-hour shift care.",
  who=["People who need help during the day but usually sleep through the night","Couples who want to stay together at home","Families who value one consistent caregiver relationship","Rural areas where shift coverage is hard to staff"],
  includes=["Personal care, meals, housekeeping and laundry","Medication reminders and appointment escorts","Companionship and routine building","Overnight presence for occasional needs","Rotation with a relief caregiver for days off"],
  cost="Live-in care is usually billed as a daily rate. Labor rules differ by U.S. state, Canadian province and country — most require an unpaid sleep period of at least 8 hours with at least 5 uninterrupted, plus meal breaks. If night-time help is needed regularly, 24-hour shift care is the safer (and legally cleaner) model.",
  faqs=[("Does a live-in caregiver need their own room?","Yes. A private, furnished bedroom and access to a bathroom and kitchen are standard requirements."),
        ("What happens on the caregiver's days off?","Agencies schedule a trained relief caregiver so coverage is continuous."),
        ("Is live-in care cheaper than a care home?","Often comparable, and sometimes cheaper for couples, because two people can be supported by one caregiver.")]),
 dict(slug="overnight-care", name="Overnight Care", icon="moon", ctype="overnight",
  title="Overnight Care: Awake and Sleeping Night Caregivers",
  desc="Overnight home care options — awake night care vs sleeping night care — who needs it, what it costs and how to arrange a trusted night caregiver.",
  intro="Nights are when many families hit a wall. Overnight care places a caregiver in the home from evening to morning so your loved one is safe and you can finally sleep. There are two models: awake overnight care (the caregiver stays up) and sleeping overnight care (the caregiver rests but is on hand).",
  who=["Frequent night-time toileting or incontinence","Sundowning, restlessness or wandering after dark","Recent falls or new mobility limits","Family caregivers who are sleep-deprived","Post-surgery recovery in the first weeks home"],
  includes=["Bedtime routine and settling","Toileting assistance and repositioning","Night-time safety checks and fall prevention","Reassurance during confusion or anxiety","Morning routine handover to family or day caregiver"],
  cost="Awake night care is typically billed at the agency's hourly rate (U.S. median about $35/hour in 2025), usually with 8–12 hour minimums. Sleeping night care is often a flat night rate. Many families combine overnight care with family-provided daytime care to control costs.",
  faqs=[("Which is better — awake or sleeping night care?","If help is needed more than once or twice a night, choose awake care. Sleeping night care works when help is rare and mostly reassurance."),
        ("Can overnight care be just a few nights a week?","Yes. Many families book 2–3 nights a week so the main family caregiver gets consistent rest.")]),
 dict(slug="dementia-care", name="Dementia & Alzheimer's Care", icon="brain", ctype="dementia",
  title="Dementia & Alzheimer's Care at Home and in Memory Care",
  desc="Dementia care options at every stage — in-home dementia caregivers, memory care communities, safety, behaviour support and costs.",
  intro="Dementia changes what 'good care' looks like over time. Early on, light support and structure may be enough; in later stages, specialised, often 24-hour, care becomes essential. The right plan matches the stage, safety risks and the family's capacity.",
  who=["A new diagnosis of Alzheimer's disease or another dementia","Wandering, getting lost, or leaving the stove on","Changes in mood, sleep, or recognition of family","Caregiver stress, burnout or health decline in the family"],
  includes=["Dementia-trained caregivers using person-centred approaches","Routine, meaningful activity and cognitive engagement","Help with bathing, dressing, eating and continence","Home safety set-up and wandering prevention","Support through sundowning and distressed behaviours","Coordination with physicians, day programmes and memory care"],
  cost="Costs depend on hours and setting: in-home care (U.S. median about $35/hour), adult day programmes (about $95/day) and memory care communities, which usually cost more than standard assisted living ($6,200/month median for assisted living in 2025, CareScout). Use the calculator to compare.",
  faqs=[("When is it time for memory care?","Common triggers are safety risks the home cannot manage (wandering, falls, aggression), needs that exceed what family and in-home caregivers can cover, or the caregiver's own health failing."),
        ("Are home caregivers trained in dementia care?","Training varies widely. Ask agencies what dementia training their caregivers complete, how many hours, and how they handle behaviours like refusal or exit-seeking."),
        ("Where can we get free dementia support?","In the U.S., the Alzheimer's Association runs a 24/7 Helpline (1-800-272-3900). In Canada, contact your provincial Alzheimer Society.")]),
 dict(slug="personal-companion-care", name="Personal & Companion Care", icon="hand", ctype="personal",
  title="Personal Care & Companion Care at Home",
  desc="What personal care and companion care include, who they're for, typical hourly costs and how to choose a reliable home care agency.",
  intro="Personal and companion care are the foundation of in-home support. Companion care covers social connection, errands, meals and light housekeeping. Personal care adds hands-on help with activities of daily living (ADLs) such as bathing, dressing and toileting.",
  who=["Older adults living alone who are isolated or lonely","People who need help with bathing or dressing","Those who no longer drive and need help with errands","Families who need a few reliable hours of help each week"],
  includes=["Companionship, conversation, hobbies and outings","Meal planning, cooking and grocery shopping","Light housekeeping and laundry","Bathing, grooming, dressing and toileting","Transportation and appointment escorts","Medication reminders"],
  cost="Most agencies charge hourly with a 2–4 hour minimum visit. The U.S. national median for non-medical in-home care is about $35/hour (CareScout 2025); rates vary significantly by city.",
  faqs=[("How many hours of care will we need?","Start by listing tasks that are unsafe or not getting done, then time them. Many families start with 12–20 hours per week and adjust."),
        ("Can we hire privately instead of using an agency?","Yes, but you become the employer — responsible for background checks, payroll taxes, insurance and backup coverage. Agencies cost more per hour but handle all of this.")]),
 dict(slug="post-hospital-respite-care", name="Post-Hospital & Respite Care", icon="hospital", ctype="post-hospital",
  title="Post-Hospital Transition Care & Respite Care",
  desc="Safe hospital-to-home transitions and respite care for exhausted family caregivers — options, costs and how to book short-term help.",
  intro="The first 30 days after a hospital stay carry the highest risk of complications and readmission. Transitional care at home and short-term respite care help people recover safely while giving family caregivers essential relief.",
  who=["Discharge after surgery, stroke, heart failure or pneumonia","Family caregivers who need a break, vacation or time to work","Short-term care while a family caregiver recovers from their own illness"],
  includes=["Discharge pick-up and home set-up","Medication reminders aligned with the discharge plan","Help with mobility, bathing and meals during recovery","Monitoring and reporting warning signs to family and clinicians","Planned respite blocks — hours, overnights or several days"],
  cost="Short-term home care is billed hourly. Some residential communities offer respite stays by the day or week. In the U.S., Medicare may cover skilled home health after a qualifying hospital stay when ordered by a doctor; custodial help is usually private-pay.",
  faqs=[("How soon should we arrange care before discharge?","As soon as a discharge date is discussed — ideally 2–3 days before. Ask the hospital case manager for the written discharge plan."),
        ("Is respite care only for dementia?","No. Respite care supports any family caregiver who needs a break, regardless of the care recipient's condition.")]),
 dict(slug="assisted-living-memory-care", name="Assisted Living & Memory Care", icon="building", ctype="assisted-living",
  title="Assisted Living & Memory Care: Compare Communities",
  desc="How to compare assisted living and memory care communities — costs, levels of care, tour questions and when a move makes sense.",
  intro="When care needs outgrow what is realistic at home — or isolation becomes the bigger risk — a residential community can offer 24/7 staff, meals, activities and social life. Memory care communities add secure environments and dementia-specialised staff.",
  who=["People needing daily help but not continuous medical care","Those isolated at home or struggling with meals and home upkeep","Dementia with wandering risk (memory care)","Couples with different care needs who want to live nearby"],
  includes=["Private or shared apartments","24-hour staff and emergency response","Meals, housekeeping and laundry","Help with ADLs and medication management","Social, fitness and cognitive programmes","Secure units and specialised staff in memory care"],
  cost="The U.S. national median for assisted living was about $6,200 per month in 2025 (CareScout). Memory care typically adds a premium. Nursing homes, which provide 24-hour skilled nursing, run about $315/day semi-private and $355/day private.",
  faqs=[("What should we ask on a tour?","Staff-to-resident ratios by shift, staff turnover, how care levels are assessed and priced, what happens if needs increase, recent inspection reports, and all fees beyond base rent."),
        ("Does a referral service cost families money?","Reputable referral services are free to families because communities pay them a fee. Always ask how they are compensated — see our How We Make Money page.")]),
 dict(slug="palliative-hospice-support", name="Palliative & Hospice Support", icon="leaf", ctype="palliative",
  title="Palliative Care & Hospice Support at Home",
  desc="Understand palliative care vs hospice, what's covered, and how in-home caregivers support comfort, dignity and family at end of life.",
  intro="Palliative care focuses on comfort and quality of life during serious illness and can start at any stage. Hospice is palliative care for people with a limited life expectancy who are no longer seeking curative treatment. Private caregivers can complement the hospice team with extra hours at home.",
  who=["Serious illness with pain, breathlessness or fatigue","People who want to remain at home for end-of-life care","Families needing extra hands between hospice nurse visits"],
  includes=["Comfort-focused personal care and repositioning","Companionship and vigil support","Respite for family members","Coordination with the hospice nurse and physician","Light housekeeping and meals for the household"],
  cost="In the U.S., the Medicare hospice benefit covers the hospice team, medications and equipment related to the terminal illness, but not 24-hour custodial caregivers. Many families add private-pay caregivers for nights or longer shifts.",
  faqs=[("Does choosing hospice mean giving up?","No. Hospice shifts the focus to comfort and dignity. Patients can leave hospice and resume curative treatment if they choose."),
        ("Can we get 24-hour help during the final days?","Hospice may provide continuous home care during short periods of crisis; otherwise families combine hospice with private caregivers.")]),
]
